# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publ', models.DateTimeField()),
                ('plecat_din', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self', to='post.Country')),
                ('sosit_in', models.ManyToManyField(related_name='post', to='post.Country')),
            ],
        ),
    ]
