# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='plecat_din',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plecat', to='post.Country'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='sosit_in',
        ),
        migrations.AddField(
            model_name='post',
            name='sosit_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sosit', to='post.Country'),
        ),
    ]
