# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170502_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Denumire')),
                ('price', models.FloatField(verbose_name='Price')),
                ('in_stock', models.BooleanField(db_index=True, default=True, verbose_name='Stoc')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publ',
            field=models.DateTimeField(auto_now=True, verbose_name='data postarii'),
        ),
    ]
