# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170502_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='part',
            field=models.IntegerField(blank=True, choices=[(1, 'US'), (2, 'EU'), (3, 'REST')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='plecat_din',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plecat', to='post.Country'),
        ),
    ]
