# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20170516_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['name', '-price']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data_publ'], 'verbose_name': 'Postari transport'},
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
